version: "3.8"
services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=raspberrypi.local

      # Optional:

      # Allow api to directly communicate by this access key using "x-api-key" header
      # - API_KEY=ABCDEFG

      # hcaptcha
      # - HCAPTCHA_SITE_KEY=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
      # - HCAPTCHA_SECRET=0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      # - PASSWORD=foobar123
      # - SERVER_DESCRIPTION=WG1
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24


    image: jovanshelomo/wg-easy-improved
    container_name: wg-easy-improved
    volumes:
      - .:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
